### ISSUE TITLE
Missing dependancies (ack and cloc) while running batch_score.py

### ISSUE THREAD

**Issue by nasifimtiazohi** [RepoReapers/reaper#15]
I ran the command -
`sudo python3 batch_score.py  -c config.json -r /repos_path -m manifest.json -s idds.txt`

where I changed the config.json and idds.txt contains a set of integers as ids. I did not touch manifest.json and wrote /repos_path as the code should make the directory itself. Although I didn't understand the use of -r <repos_path> parameter.

The output I get,

```
#########################
           Run           
#########################
[architecture] Dependency ack missing
[unit_test] Dependency cloc missing
Traceback (most recent call last):
  File "/Users/adminuser/Desktop/reaper/lib/run.py", line 31, in run
    self.attributes.global_init(samples)
  File "/Users/adminuser/Desktop/reaper/lib/attributes.py", line 70, in global_init
    'Missing dependencies must be installed to continue.'
Exception: Missing dependencies must be installed to continue.
```

P.S. I ran the requirements.txt. 
Although I had to change line 1 
from 
`mysql-connector-python>=2.0.3,<3.0`
to
`http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip`
as I was getting an error while installing the library and I took the accepted solution from https://stackoverflow.com/questions/34489271/i-cannot-install-mysql-connector-python-using-pip

after that it shows all requirements satisfied.

running `pip3 install -r requirements.txt`, I get,

```
Collecting http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip (from -r requirements.txt (line 1))
  Using cached http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip
  Requirement already satisfied (use --upgrade to upgrade): mysql-connector-python==2.1.4 from http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Pygments<3.0,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: networkx<2.0,>=1.9.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: APScheduler<4.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pandas<1.0,>=0.16.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: python-dateutil<3.0,>=2.4.2 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.6/site-packages (from networkx<2.0,>=1.9.1->-r requirements.txt (line 3))
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.6/site-packages (from APScheduler<4.0,>=3.0.2->-r requirements.txt (line 4))
Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.6/site-packages (from APScheduler<4.0,>=3.0.2->-r requirements.txt (line 4))
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from APScheduler<4.0,>=3.0.2->-r requirements.txt (line 4))
Requirement already satisfied: six>=1.4.0 in /Users/adminuser/Library/Python/3.6/lib/python/site-packages (from APScheduler<4.0,>=3.0.2->-r requirements.txt (line 4))
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.6/site-packages (from pandas<1.0,>=0.16.0->-r requirements.txt (line 5))
Building wheels for collected packages: mysql-connector-python
  Running setup.py bdist_wheel for mysql-connector-python ... done
  Stored in directory: /Users/adminuser/Library/Caches/pip/wheels/2d/a1/d4/f935ca605a52b5291a8a1a4d12f635bdff2e965235b30e099c
Successfully built mysql-connector-python
```

**Comment by rpecka** [comment]
I had the same issue. I was able to resolve it by installing those dependencies with Homebrew

**Comment by nuthanmunaiah** [comment]
Note the first two lines of information in the output you posted:

```
#########################
           Run           
#########################
[architecture] Dependency ack missing
[unit_test] Dependency cloc missing
...
```

The _Architecture_ and _Unit Testing_ attributes depend on `ack` (https://beyondgrep.com/) and `cloc` (https://github.com/AlDanial/cloc), respectively. `reaper` checks for dependencies before attempting to do anything else. You must either install these dependencies or disable the attributes to continue.

**Comment by nasifimtiazohi** [comment]
installing ack and cloc through homebrew solved the issue.
Although, I'm still getting errors on python module import,
I'll close this issue.
